const users = [
  {
    id: 1234567,
    firstName: "Charafi",
    lastname: "Chanfi",
    profession: "Future developer",
    age: 31,
    email: "charafi.chanfi@gmail.com",
    status: "Married",
    salaire: 5500,
    friends: [],
    profilePhoto: "https://github.com/mdo.png",
    phone: "+33 6 12 34 56 01",
  },
  {
    id: 123451011,
    firstName: "Malek",
    lastname: "BEN ANES",
    profession: "Developer",
    age: 28,
    email: "malek.benanes@outlook.com",
    status: "Single",
    salaire: 4200,
    friends: [],
    profilePhoto: "https://github.com/gaearon.png",
    phone: "+33 6 12 34 56 02",
  },
  {
    id: 1234568,
    firstName: "Sofia",
    lastname: "Benali",
    profession: "UI Designer",
    age: 28,
    email: "sofia.benali@gmail.com",
    status: "Single",
    salaire: 4200,
    friends: [],
    profilePhoto: "https://github.com/gaearon.png",
    phone: "+33 6 12 34 56 02",
  },
  {
    id: 1234569,
    firstName: "Yassine",
    lastname: "El Amrani",
    profession: "Backend Developer",
    age: 35,
    email: "yassine.elamrani@gmail.com",
    status: "Married",
    salaire: 6100,
    friends: [],
    profilePhoto: "https://github.com/yyx990803.png",
    phone: "+33 6 12 34 56 03",
  },
  {
    id: 1234570,
    firstName: "Nadia",
    lastname: "Karimi",
    profession: "Data Analyst",
    age: 30,
    email: "nadia.karimi@gmail.com",
    status: "Single",
    salaire: 4800,
    friends: [],
    profilePhoto: "https://github.com/torvalds.png",
    phone: "+33 6 12 34 56 04",
  },
  {
    id: 1234571,
    firstName: "Karim",
    lastname: "Bouzidi",
    profession: "DevOps Engineer",
    age: 33,
    email: "karim.bouzidi@gmail.com",
    status: "Married",
    salaire: 6700,
    friends: [],
    profilePhoto: "https://github.com/defunkt.png",
    phone: "+33 6 12 34 56 05",
  },
  {
    id: 1234572,
    firstName: "Leila",
    lastname: "Mansouri",
    profession: "Frontend Developer",
    age: 26,
    email: "leila.mansouri@gmail.com",
    status: "Single",
    salaire: 3900,
    friends: [],
    profilePhoto: "https://github.com/octocat.png",
    phone: "+33 6 12 34 56 06",
  },
  {
    id: 1234573,
    firstName: "Amine",
    lastname: "Rahmani",
    profession: "Mobile Developer",
    age: 29,
    email: "amine.rahmani@gmail.com",
    status: "In relationship",
    salaire: 5100,
    friends: [],
    profilePhoto: "https://github.com/mojombo.png",
    phone: "+33 6 12 34 56 07",
  },
  {
    id: 1234574,
    firstName: "Sarah",
    lastname: "Khaldi",
    profession: "Product Manager",
    age: 32,
    email: "sarah.khaldi@gmail.com",
    status: "Married",
    salaire: 7200,
    friends: [],
    profilePhoto: "https://github.com/pjhyett.png",
    phone: "+33 6 12 34 56 08",
  },
  {
    id: 1234575,
    firstName: "Mehdi",
    lastname: "Touati",
    profession: "Cybersecurity Engineer",
    age: 37,
    email: "mehdi.touati@gmail.com",
    status: "Single",
    salaire: 7500,
    friends: [],
    profilePhoto: "https://github.com/jakewharton.png",
    phone: "+33 6 12 34 56 09",
  },
  {
    id: 1234576,
    firstName: "Ines",
    lastname: "Cherif",
    profession: "QA Engineer",
    age: 27,
    email: "ines.cherif@gmail.com",
    status: "Single",
    salaire: 4100,
    friends: [],
    profilePhoto: "https://github.com/sindresorhus.png",
    phone: "+33 6 12 34 56 10",
  },
];

export const signIn = (emailInput) => {
  return users.find((user) => user.email === emailInput);
};

export const getUserById = (idInput) => {
  const idNumber = parseInt(idInput);
  return users.find((user) => user.id === idNumber);
};
